title: Pentest Road
description: Stuff are coming..
author: Hugo Pons
url: https://hpons01.github.io

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  writeups:
    output: true
    permalink: /writeups/:year/:month/:day/:title/
